class_name VignetteFigures
## Frame layout of the vignette footballer sheets (assets/vignette/figures_*.png).
## GENERATED by ard-asset-pipeline (tools/combine_sheets.py) - rebuild, don't edit by hand.
##
## figures_shade.png: R lighting, G hair weight, B shorts weight, A coverage.
## figures_mask.png:  R club primary, G club secondary, B skin, A coverage.
## Boots take the weight left over. Each body is a block of rows: one row per
## animation and facing ("front" faces the camera, "back" shows the number),
## frames left to right. number_rects: where the number sits on a back-facing
## frame, [x, y, w, h] in frame pixels.

const SHEET_SIZE := Vector2i(2048, 2304)
const FRAME := Vector2(128, 288)
## World (0, 0, 0) - the feet - in every frame, pixels.
const PIVOT := Vector2(64.00, 266.16)
const PX_PER_M := 100.0
const BODIES := {
	"average": {
		"x": 0,
		"height_m": 1.88,
		"anims": {
			"idle": {
				"front": {
					"row": 0,
					"frames": 1,
					"number_rects": [],
				},
				"back": {
					"row": 1,
					"frames": 1,
					"number_rects": [[42, 114, 45, 49]],
				},
			},
			"jog": {
				"front": {
					"row": 2,
					"frames": 8,
					"number_rects": [],
				},
				"back": {
					"row": 3,
					"frames": 8,
					"number_rects": [[41, 111, 46, 50], [41, 119, 46, 49], [42, 124, 45, 49], [41, 119, 46, 49], [41, 111, 46, 50], [41, 119, 46, 49], [41, 124, 46, 49], [41, 119, 46, 49]],
				},
			},
			"leap": {
				"front": {
					"row": 4,
					"frames": 6,
					"number_rects": [],
				},
				"back": {
					"row": 5,
					"frames": 6,
					"number_rects": [[41, 129, 46, 49], [41, 116, 46, 49], [42, 115, 44, 48], [38, 116, 52, 47], [40, 116, 48, 47], [40, 116, 48, 39]],
				},
			},
			"bounce": {
				"front": {
					"row": 6,
					"frames": 4,
					"number_rects": [],
				},
				"back": {
					"row": 7,
					"frames": 4,
					"number_rects": [[42, 115, 44, 48], [43, 116, 42, 47], [41, 113, 46, 49], [41, 113, 46, 49]],
				},
			},
		},
	},
	"ruck": {
		"x": 1024,
		"height_m": 2.03,
		"anims": {
			"idle": {
				"front": {
					"row": 0,
					"frames": 1,
					"number_rects": [],
				},
				"back": {
					"row": 1,
					"frames": 1,
					"number_rects": [[40, 102, 48, 51]],
				},
			},
			"jog": {
				"front": {
					"row": 2,
					"frames": 8,
					"number_rects": [],
				},
				"back": {
					"row": 3,
					"frames": 8,
					"number_rects": [[40, 98, 48, 53], [40, 106, 48, 53], [40, 112, 48, 53], [40, 106, 48, 53], [40, 98, 48, 53], [40, 106, 48, 53], [40, 112, 48, 53], [40, 106, 48, 53]],
				},
			},
			"leap": {
				"front": {
					"row": 4,
					"frames": 6,
					"number_rects": [],
				},
				"back": {
					"row": 5,
					"frames": 6,
					"number_rects": [[39, 117, 50, 53], [40, 103, 48, 53], [40, 102, 48, 52], [37, 103, 54, 51], [38, 103, 52, 51], [38, 103, 52, 42]],
				},
			},
			"bounce": {
				"front": {
					"row": 6,
					"frames": 4,
					"number_rects": [],
				},
				"back": {
					"row": 7,
					"frames": 4,
					"number_rects": [[40, 103, 48, 51], [41, 104, 46, 50], [40, 100, 48, 53], [39, 100, 50, 52]],
				},
			},
		},
	},
}
