class_name VignetteFigures
## Frame layout of the vignette footballer sheets (assets/vignette/figures_*.png).
## GENERATED by ard-asset-pipeline (tools/combine_sheets.py) - rebuild, don't edit by hand.
##
## figures_shade.png:  R lighting, G hair weight, B shorts weight, A coverage.
## figures_mask.png:   R guernsey base colour (guernsey + socks), G sock band, B skin, A guernsey alone.
## figures_design.png: (half size) R across the guernsey, G up it, B front/back - for club designs.
## Boots take the weight left over. Each body is a block of rows: one row per
## animation and facing ("front" faces the camera, "back" shows the number),
## frames left to right. number_rects: where the number sits on a back-facing
## frame, [x, y, w, h] in frame pixels.

const SHEET_SIZE := Vector2i(2048, 2304)
const FRAME := Vector2(128, 288)
## World (0, 0, 0) - the feet - in every frame, pixels.
const PIVOT := Vector2(64.00, 266.16)
const PX_PER_M := 100.0
const BODIES := {
	"average": {
		"x": 0,
		"height_m": 1.88,
		"anims": {
			"idle": {
				"front": {
					"row": 0,
					"frames": 1,
					"number_rects": [],
				},
				"back": {
					"row": 1,
					"frames": 1,
					"number_rects": [[43, 114, 42, 49]],
				},
			},
			"jog": {
				"front": {
					"row": 2,
					"frames": 8,
					"number_rects": [],
				},
				"back": {
					"row": 3,
					"frames": 8,
					"number_rects": [[43, 111, 42, 50], [42, 119, 43, 49], [42, 124, 43, 49], [42, 119, 43, 49], [43, 111, 42, 50], [43, 119, 43, 49], [43, 124, 43, 49], [43, 119, 43, 49]],
				},
			},
			"leap": {
				"front": {
					"row": 4,
					"frames": 6,
					"number_rects": [],
				},
				"back": {
					"row": 5,
					"frames": 6,
					"number_rects": [[42, 129, 44, 49], [43, 116, 42, 50], [43, 114, 42, 50], [39, 114, 50, 50], [41, 114, 46, 50], [41, 114, 46, 41]],
				},
			},
			"bounce": {
				"front": {
					"row": 6,
					"frames": 4,
					"number_rects": [],
				},
				"back": {
					"row": 7,
					"frames": 4,
					"number_rects": [[43, 115, 42, 49], [43, 117, 42, 47], [42, 114, 44, 48], [42, 113, 44, 49]],
				},
			},
		},
	},
	"ruck": {
		"x": 1024,
		"height_m": 2.03,
		"anims": {
			"idle": {
				"front": {
					"row": 0,
					"frames": 1,
					"number_rects": [],
				},
				"back": {
					"row": 1,
					"frames": 1,
					"number_rects": [[41, 102, 46, 52]],
				},
			},
			"jog": {
				"front": {
					"row": 2,
					"frames": 8,
					"number_rects": [],
				},
				"back": {
					"row": 3,
					"frames": 8,
					"number_rects": [[41, 99, 46, 52], [41, 106, 46, 53], [41, 112, 46, 53], [41, 106, 46, 53], [41, 99, 46, 52], [41, 106, 46, 53], [41, 112, 46, 53], [41, 106, 46, 53]],
				},
			},
			"leap": {
				"front": {
					"row": 4,
					"frames": 6,
					"number_rects": [],
				},
				"back": {
					"row": 5,
					"frames": 6,
					"number_rects": [[41, 117, 46, 54], [41, 103, 46, 54], [42, 102, 44, 52], [37, 102, 54, 52], [39, 102, 50, 52], [39, 102, 50, 43]],
				},
			},
			"bounce": {
				"front": {
					"row": 6,
					"frames": 4,
					"number_rects": [],
				},
				"back": {
					"row": 7,
					"frames": 4,
					"number_rects": [[41, 103, 46, 51], [41, 105, 46, 49], [41, 101, 46, 52], [41, 100, 47, 53]],
				},
			},
		},
	},
}
